version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: board-mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: board
      MYSQL_USER: board
      MYSQL_PASSWORD: board1234
      TZ: Asia/Seoul

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data: